// Generated by gencpp from file speech_synthesis/synthesis_serviceResponse.msg
// DO NOT EDIT!


#ifndef SPEECH_SYNTHESIS_MESSAGE_SYNTHESIS_SERVICERESPONSE_H
#define SPEECH_SYNTHESIS_MESSAGE_SYNTHESIS_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speech_synthesis
{
template <class ContainerAllocator>
struct synthesis_serviceResponse_
{
  typedef synthesis_serviceResponse_<ContainerAllocator> Type;

  synthesis_serviceResponse_()
    : res(0)  {
    }
  synthesis_serviceResponse_(const ContainerAllocator& _alloc)
    : res(0)  {
  (void)_alloc;
    }



   typedef int32_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct synthesis_serviceResponse_

typedef ::speech_synthesis::synthesis_serviceResponse_<std::allocator<void> > synthesis_serviceResponse;

typedef boost::shared_ptr< ::speech_synthesis::synthesis_serviceResponse > synthesis_serviceResponsePtr;
typedef boost::shared_ptr< ::speech_synthesis::synthesis_serviceResponse const> synthesis_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace speech_synthesis

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca16cfbd5443ad97f6cc7ffd6bb67292";
  }

  static const char* value(const ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca16cfbd5443ad97ULL;
  static const uint64_t static_value2 = 0xf6cc7ffd6bb67292ULL;
};

template<class ContainerAllocator>
struct DataType< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech_synthesis/synthesis_serviceResponse";
  }

  static const char* value(const ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 res\n\
\n\
";
  }

  static const char* value(const ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct synthesis_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech_synthesis::synthesis_serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<int32_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_SYNTHESIS_MESSAGE_SYNTHESIS_SERVICERESPONSE_H
